### ISSUE TITLE
Representable::YAML fails

### ISSUE THREAD

**Issue by michaelmior** [apotonick/representable#179]
Trying to use `Representable::YAML` fails when I upgraded from 2.2 to 2.4. Below is a simple decorator I have defined.

```ruby
class IndexRepresenter < Representable::Decorator
  include Representable::YAML

  property :key
end
```

Then, I try to represent a simple object as below.

```ruby
require 'ostruct'
index = OpenStruct.new
index.key = 'key'
hash = IndexRepresenter.represent(index).to_hash
```

This works if I use `Representable::JSON`, but with `Representable::YAML` I get the following error:

```
     NoMethodError:
       undefined method `children' for {}:Hash
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/yaml/binding.rb:12:in `write'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/serializer.rb:47:in `block in <module:Representable>'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/pipeline.rb:18:in `call'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/pipeline.rb:18:in `evaluate'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/pipeline.rb:10:in `block in call'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/pipeline.rb:9:in `each'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/pipeline.rb:9:in `inject'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/pipeline.rb:9:in `call'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/binding.rb:36:in `compile_fragment'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/deprecations.rb:112:in `compile_fragment'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable.rb:52:in `block in call'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable.rb:50:in `each'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable.rb:50:in `call'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable.rb:69:in `representable_map!'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable.rb:44:in `create_representation_with'
     # /u1/mmior/.rvm/gems/ruby-2.1.6/gems/representable-2.4.1/lib/representable/hash.rb:34:in `to_hash'
```

Any help sorting this out would be appreciated!

**Comment by apotonick** [comment]
It must be `to_yaml` and not `to_hash`! :grimacing:

**Comment by michaelmior** [comment]
I understand that I need `to_yaml` to produce YAML. But shouldn't I be able to produce a hash using `to_hash` regardless? This used to work just fine in version 2.2.

**Comment by apotonick** [comment]
Yepp, makes sense what you say.

Can you try that without `represent` and see if that's the problem. Because, have a look at `yaml_test.rb`, it's all tested there!

**Comment by michaelmior** [comment]
Here's a complete example that fails in my project. I tried copying this file into the Representable 2.4.1 source tree and did `bundle exec ruby test.rb` and I get the failure described above.

```ruby
require 'yaml'

require 'representable'
require 'representable/json'
require 'representable/yaml'

class IndexRepresenter < Representable::Decorator
  include Representable::JSON
  # The error occurs when I uncomment the line below
  # include Representable::YAML

  property :key
end

require 'ostruct'
index = OpenStruct.new
index.key = 'key'
hash = IndexRepresenter.represent(index).to_hash
puts YAML.dump(hash)
```

**Comment by apotonick** [comment]
Sorry, in Representable 2.2 that was a bug - the `to_hash` method is not to be called in a YAML representer (even though we use `from_hash` internally). If you want a hash representation, please use `Representable::Hash`.

**Comment by michaelmior** [comment]
Thanks! Because of this bug I didn't realize `Representable::Hash` existed. This seems to have resolved my problem although the odd thing is that I need to include `Representable::Hash` *after* `Representable::YAML` for this to work but that's pretty minor.
